# Generated by Django 4.2.5 on 2023-11-03 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.exam'),
        ),
        migrations.AddField(
            model_name='student',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.country'),
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.courses'),
        ),
        migrations.AddField(
            model_name='student',
            name='district',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.district'),
        ),
        migrations.AddField(
            model_name='student',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.state'),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='state',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.country'),
        ),
        migrations.AddField(
            model_name='room',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.courses'),
        ),
        migrations.AddField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.room'),
        ),
        migrations.AddField(
            model_name='message',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='exam',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.courses'),
        ),
        migrations.AddField(
            model_name='district',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.country'),
        ),
        migrations.AddField(
            model_name='district',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AdminApp.state'),
        ),
    ]
